version: "3.7"

volumes:
  postgres_data:
  static_data:

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
    container_name: cooking_corner_app
    command: uvicorn main:app --host 0.0.0.0 --workers 1
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
