version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 5432
    expose:
      - 5432:5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: cooking_corner_app
    command: ["/CookingCorner/docker/app.sh"]
    ports:
      - 8001:8000
    depends_on:
      - db
