"""Users rating

Revision ID: be539152d786
Revises: a1a54c517680
Create Date: 2024-07-06 16:37:42.845402

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be539152d786'
down_revision: Union[str, None] = 'a1a54c517680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('users_ratings', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'users_ratings')
    # ### end Alembic commands ###
