"""Users rated

Revision ID: a1a54c517680
Revises: fdd9f5f81ff9
Create Date: 2024-07-06 15:38:46.933473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a54c517680'
down_revision: Union[str, None] = 'fdd9f5f81ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('users_rated', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'users_rated')
    # ### end Alembic commands ###
