"""ratings count

Revision ID: bc913e290698
Revises: 4431ed0fbb46
Create Date: 2024-07-09 00:01:42.386432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc913e290698'
down_revision: Union[str, None] = '4431ed0fbb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('users_ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'users_ratings_count')
    # ### end Alembic commands ###
