"""Tag not unique

Revision ID: 1e5481a4df15
Revises: e022aa23ad51
Create Date: 2024-07-02 20:15:30.000786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5481a4df15'
down_revision: Union[str, None] = 'e022aa23ad51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_name_key', 'tag', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tag_name_key', 'tag', ['name'])
    # ### end Alembic commands ###
