"""Recipe creation time

Revision ID: fdd9f5f81ff9
Revises: 494a4a12f45a
Create Date: 2024-07-05 21:08:01.901643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd9f5f81ff9'
down_revision: Union[str, None] = '494a4a12f45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('creation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'creation_time')
    # ### end Alembic commands ###
