"""portions

Revision ID: 4431ed0fbb46
Revises: 9722156b4645
Create Date: 2024-07-08 21:16:16.661568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4431ed0fbb46'
down_revision: Union[str, None] = '9722156b4645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('portions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'portions')
    # ### end Alembic commands ###
