"""recent recipes

Revision ID: 494a4a12f45a
Revises: 1e5481a4df15
Create Date: 2024-07-05 17:11:39.745622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494a4a12f45a'
down_revision: Union[str, None] = '1e5481a4df15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recent_recipes', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recent_recipes')
    # ### end Alembic commands ###
