"""Recipe name not unique

Revision ID: 2a9a6529a96a
Revises: 9c61868fc4e7
Create Date: 2024-06-28 01:08:33.997085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9a6529a96a'
down_revision: Union[str, None] = '9c61868fc4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_name_key', 'recipe', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('recipe_name_key', 'recipe', ['name'])
    # ### end Alembic commands ###
